#!/bin/bash
PATH=/opt/vim/bin:/opt/python2/bin:/opt/green/bin:/opt/docker/bin:/opt/boot/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/bin:/usr/sbin:/opt/boot/bin

SERVICE=$1 # service name aka organisation
ZPOOL=green # ZFS pool
ZDATASET=$ZPOOL/$SERVICE
ZQUOTA=50G # ZFS dataset quota
VOLUME_BASE=/data/$SERVICE # ZFS mountpoint
DOCKER_PORT=$2 # docker port to expose postgresql
TIME=$(date +%Y%m%d%H%M%S)
SQLDEST=$VOLUME_BASE/sqlbackups # destination for sql backups
REMOTE=gdrive_bout # remote rclone provider
ZFS_KEEP=+30 # delete older than (n)  ZFS snapshots


echo "==== Pravim SQL dumpall servera===="

[ -d $SQLDEST  ] || sudo mkdir -p $SQLDEST && sudo chown docker:docker $SQLDEST
docker exec  $SERVICE pg_dumpall -U postgres | gzip -c > $SQLDEST/postgresql.$TIME.sql.gz
echo "napravio $SQLDEST/postgresql.$TIME.sql.gz"

echo "==== Prebacujem $SQLDEST/postgresql.$TIME.sql.gz na G-DRIVE"

rclone copy $SQLDEST  $REMOTE:$SERVICE
echo "Prebacio:"
rclone lsl $REMOTE:$SERVICE  | head -1 | awk '{print $4}'

echo "====Pravim ZFS snapshot $ZDATASET -a ===="

echo "Obaram CT:"
docker stop $SERVICE
RUNNING=$(docker inspect --format="{{ .State.Running }}" $SERVICE 2> /dev/null)

if [ $? -eq 1 ]; then
    echo "$SERVICE CT nije pokrenut idem dalje......"
fi
if [ "$RUNNING" == "true" ]; then
    echo "$SERVICE CT je već pokrenut, provjeri...."
    exit 0
fi

echo "==== Čistim stare snapshote ===="

for S in `zfs list -t snapshot -o name -S creation | grep $ZDATASET | tail -n $ZFS_KEEP`;
do
  sudo zfs destroy -vr $S
done

sudo zfs snapshot -r $ZDATASET@$TIME
echo "Kreiran snapshot:"

sudo zfs list $ZDATASET@$TIME
echo "Startam CT:"
docker start $SERVICE

echo "==== Provjeravam ZFS snapshot ===="


sudo zfs clone $ZDATASET@$TIME  $ZDATASET-clone
du -sh /$ZDATASET-clone
sudo zfs unmount $ZDATASET-clone
sudo zfs destroy $ZDATASET-clone
exit
