#! /bin/bash 

# help
if [ $# -lt 1 ]
then
  echo "argumenti su:   ./greenbox_usb_update  [GREENBOX_VER]"
  echo " npr:   ./greenbox_usb_create 3.7.2"
  exit 1
fi

GREEN_ISO=http://download.bring.out.ba/greenbox-$1.iso
GREEN_CFG=/media/syslinux.cfg
DEF_BOOT=`cat $GREEN_CFG | grep "^default boot" | awk '{print $2}'`
ISO_MNT=/tmp/$1
BOOT_PATH=/media/boot

echo "defaultni boot je $DEF_BOOT"
cd  /tmp &&  wget $GREEN_ISO
rm -rf $ISO_MNT && mkdir $ISO_MNT
mount -o loop /tmp/greenbox-$1.iso  $ISO_MNT
rm -rf $BOOT_PATH/$1 && mkdir $BOOT_PATH/$1 && cd $BOOT_PATH/$1
cp -a $ISO_MNT/boot/initrd.img . 
cp -a $ISO_MNT/boot/vmlinuz64 . 
umount $ISO_MNT 
rm -rf $ISO_MNT


echo "label boot$1" >> $GREEN_CFG
echo "label greenbox-$1" >> $GREEN_CFG
echo "kernel /boot/$1/vmlinuz64"  >> $GREEN_CFG
echo "append initrd=/boot/$1/initrd.img loglevel=3 dockerpwd=test01 nozswap nofstab tz=CET-1CEST,M3.5.0,M10.5.0/3 noembed nomodeset norestore waitusb=10 LABEL=GREEN_HDD console=ttyS0,115200n8"  >> $GREEN_CFG
echo ""  >> $GREEN_CFG
sed -i -e  's/default '"$DEF_BOOT"'/default boot'"$1"'/' $GREEN_CFG
